language: csharp
solution: ceilidh-core.sln
mono: none
dotnet: 2.1.401
os:
  - linux
  - osx
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test ProjectCeilidh.NativeTK.Tests/ProjectCeilidh.NativeTK.Tests.csproj
