version: '0.0.{build}'
image: Visual Studio 2017
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore
build_script:
  - cmd: dotnet build
test_script:
  - cmd: dotnet test ProjectCeilidh.NativeTK.Tests/ProjectCeilidh.NativeTK.Tests.csproj
deploy: off